/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Cad.Cad_Livros;
import View.Cad.Cad_Bibliotecario;
import View.Cad.Cad_Categoria;
import View.Cad.Cad_Editora;
import View.Cad.Cad_Emprestimo;
import View.Cad.Cad_Autor;
import View.Cad.Cad_Cliente;
import View.Listar.ListarCliente;
import View.Listar.ListarLivro;
import View.Listar.ListarEditora;
import View.Listar.ListarAutor;
import View.Listar.ListarEmprestimo;
import View.Listar.ListarCategoria;
import View.Listar.ListarBibliotecario;
import javax.swing.JOptionPane;

/**
 *
 * @author andrey
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCliente = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnLivro = new javax.swing.JButton();
        btnBibliotecario = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnEditora = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuCliente = new javax.swing.JMenu();
        JCad_Cliente = new javax.swing.JMenuItem();
        JVisuClientes = new javax.swing.JMenuItem();
        JAlt_Cliente = new javax.swing.JMenuItem();
        JMenuLivro = new javax.swing.JMenu();
        JCad_Livro = new javax.swing.JMenuItem();
        JVisuLivro = new javax.swing.JMenuItem();
        JAlt_Livro = new javax.swing.JMenuItem();
        JMenuEmprestimo = new javax.swing.JMenu();
        JCad_Emprestimo = new javax.swing.JMenuItem();
        JVisuEmprestimos = new javax.swing.JMenuItem();
        JAlt_Emprestimo = new javax.swing.JMenuItem();
        JMenuBiblio = new javax.swing.JMenu();
        JCad_Biblio = new javax.swing.JMenuItem();
        JVisuBiblio = new javax.swing.JMenuItem();
        JAlt_Bibliotecario = new javax.swing.JMenuItem();
        JMenuAutor = new javax.swing.JMenu();
        JCadAutor = new javax.swing.JMenuItem();
        JVisuAutor = new javax.swing.JMenuItem();
        JAlt_Autor = new javax.swing.JMenuItem();
        JMenuCategoria = new javax.swing.JMenu();
        JCad_Categoria = new javax.swing.JMenuItem();
        JVisuCategorias = new javax.swing.JMenuItem();
        JAlt_Categoria = new javax.swing.JMenuItem();
        JMenuEditora = new javax.swing.JMenu();
        JCad_Editora = new javax.swing.JMenuItem();
        JVisuEditoras = new javax.swing.JMenuItem();
        JAlt_Editora = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(51, 0, 204));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cliente.png"))); // NOI18N
        btnCliente.setText("jButton1");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/emprestimo.png"))); // NOI18N
        btnEmprestimo.setText("jButton2");
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        btnLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/livros.png"))); // NOI18N
        btnLivro.setText("jButton3");
        btnLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroActionPerformed(evt);
            }
        });

        btnBibliotecario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/bibliotecario.png"))); // NOI18N
        btnBibliotecario.setText("jButton4");
        btnBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecarioActionPerformed(evt);
            }
        });

        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/autor.png"))); // NOI18N
        btnAutor.setText("jButton5");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/categoria.png"))); // NOI18N
        btnCategoria.setText("jButton6");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/editora.png"))); // NOI18N
        btnEditora.setText("jButton7");
        btnEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditoraActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/sair.png"))); // NOI18N
        btnSair.setText("jButton8");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/estantelivros.png"))); // NOI18N

        jMenu1.setText("Opções");

        JMenuCliente.setText("Clientes");

        JCad_Cliente.setText("Cadastro de Clientes");
        JCad_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_ClienteActionPerformed(evt);
            }
        });
        JMenuCliente.add(JCad_Cliente);

        JVisuClientes.setText("Visualizar Clientes");
        JVisuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuClientesActionPerformed(evt);
            }
        });
        JMenuCliente.add(JVisuClientes);

        JAlt_Cliente.setText("Alterar Cliente");
        JAlt_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_ClienteActionPerformed(evt);
            }
        });
        JMenuCliente.add(JAlt_Cliente);

        jMenu1.add(JMenuCliente);

        JMenuLivro.setText("Livros");

        JCad_Livro.setText("Cadastro de Livros");
        JCad_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_LivroActionPerformed(evt);
            }
        });
        JMenuLivro.add(JCad_Livro);

        JVisuLivro.setText("Visualizar Livros");
        JVisuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuLivroActionPerformed(evt);
            }
        });
        JMenuLivro.add(JVisuLivro);

        JAlt_Livro.setText("Alterar Livro");
        JAlt_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_LivroActionPerformed(evt);
            }
        });
        JMenuLivro.add(JAlt_Livro);

        jMenu1.add(JMenuLivro);

        JMenuEmprestimo.setText("Empréstimo");

        JCad_Emprestimo.setText("Cadastrar Empréstimo");
        JCad_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_EmprestimoActionPerformed(evt);
            }
        });
        JMenuEmprestimo.add(JCad_Emprestimo);

        JVisuEmprestimos.setText("Visualizar Empréstimos");
        JVisuEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuEmprestimosActionPerformed(evt);
            }
        });
        JMenuEmprestimo.add(JVisuEmprestimos);

        JAlt_Emprestimo.setText("Alterar Empréstimo");
        JAlt_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_EmprestimoActionPerformed(evt);
            }
        });
        JMenuEmprestimo.add(JAlt_Emprestimo);

        jMenu1.add(JMenuEmprestimo);

        JMenuBiblio.setText("Bibliotécario");

        JCad_Biblio.setText("Cadastro de Bibliotecários");
        JCad_Biblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_BiblioActionPerformed(evt);
            }
        });
        JMenuBiblio.add(JCad_Biblio);

        JVisuBiblio.setText("Visualizar Bibliotecários");
        JVisuBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuBiblioActionPerformed(evt);
            }
        });
        JMenuBiblio.add(JVisuBiblio);

        JAlt_Bibliotecario.setText("Alterar Bibliotecário");
        JAlt_Bibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_BibliotecarioActionPerformed(evt);
            }
        });
        JMenuBiblio.add(JAlt_Bibliotecario);

        jMenu1.add(JMenuBiblio);

        JMenuAutor.setText("Autor");

        JCadAutor.setText("Cadastro de Autor");
        JCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadAutorActionPerformed(evt);
            }
        });
        JMenuAutor.add(JCadAutor);

        JVisuAutor.setText("Visualizar Autores");
        JVisuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuAutorActionPerformed(evt);
            }
        });
        JMenuAutor.add(JVisuAutor);

        JAlt_Autor.setText("Alterar Autores");
        JAlt_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_AutorActionPerformed(evt);
            }
        });
        JMenuAutor.add(JAlt_Autor);

        jMenu1.add(JMenuAutor);

        JMenuCategoria.setText("Categoria");

        JCad_Categoria.setText("Cadastro de Categorias");
        JCad_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_CategoriaActionPerformed(evt);
            }
        });
        JMenuCategoria.add(JCad_Categoria);

        JVisuCategorias.setText("Visualizar Categorias");
        JVisuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuCategoriasActionPerformed(evt);
            }
        });
        JMenuCategoria.add(JVisuCategorias);

        JAlt_Categoria.setText("Alterar Categorias");
        JAlt_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_CategoriaActionPerformed(evt);
            }
        });
        JMenuCategoria.add(JAlt_Categoria);

        jMenu1.add(JMenuCategoria);

        JMenuEditora.setText("Editora");

        JCad_Editora.setText("Cadastro de Editoras");
        JCad_Editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCad_EditoraActionPerformed(evt);
            }
        });
        JMenuEditora.add(JCad_Editora);

        JVisuEditoras.setText("Visualizar Editoras");
        JVisuEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVisuEditorasActionPerformed(evt);
            }
        });
        JMenuEditora.add(JVisuEditoras);

        JAlt_Editora.setText("Alterar Editoras");
        JAlt_Editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlt_EditoraActionPerformed(evt);
            }
        });
        JMenuEditora.add(JAlt_Editora);

        jMenu1.add(JMenuEditora);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Relatórios");

        jMenu33.setText("Livros");

        jMenu37.setText("Por Autores");
        jMenu33.add(jMenu37);

        jMenu38.setText("Por Categorias");
        jMenu33.add(jMenu38);

        jMenu3.add(jMenu33);

        jMenu34.setText("Editoras");

        jMenu39.setText("Por Estados");
        jMenu34.add(jMenu39);

        jMenu3.add(jMenu34);

        jMenu32.setText("Por Data");
        jMenu3.add(jMenu32);

        jMenu35.setText("Por Entrada");
        jMenu3.add(jMenu35);

        jMenu36.setText("Por Saída");
        jMenu3.add(jMenu36);

        jMenuBar1.add(jMenu3);

        jMenu11.setText("Ajuda");
        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        // TODO add your handling code here:
        
        new Cad_Autor().setVisible(true);
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        new Cad_Cliente().setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecarioActionPerformed
        // TODO add your handling code here:
        new Cad_Bibliotecario().setVisible(true);
    }//GEN-LAST:event_btnBibliotecarioActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        new Cad_Categoria().setVisible(true);
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditoraActionPerformed
        // TODO add your handling code here:
        new Cad_Editora().setVisible(true);
    }//GEN-LAST:event_btnEditoraActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        // TODO add your handling code here:
        new Cad_Emprestimo().setVisible(true);
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroActionPerformed
        // TODO add your handling code here:
        new Cad_Livros().setVisible(true);
    }//GEN-LAST:event_btnLivroActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        
        if(sair == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void JVisuBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuBiblioActionPerformed
        new ListarBibliotecario().setVisible(true);
    }//GEN-LAST:event_JVisuBiblioActionPerformed

    private void JVisuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuAutorActionPerformed
        new ListarAutor().setVisible(true);
    }//GEN-LAST:event_JVisuAutorActionPerformed

    private void JVisuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuCategoriasActionPerformed
        new ListarCategoria().setVisible(true);
    }//GEN-LAST:event_JVisuCategoriasActionPerformed

    private void JVisuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuClientesActionPerformed
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_JVisuClientesActionPerformed

    private void JVisuEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuEditorasActionPerformed
        new ListarEditora().setVisible(true);
    }//GEN-LAST:event_JVisuEditorasActionPerformed

    private void JVisuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuLivroActionPerformed
        new ListarLivro().setVisible(true);
    }//GEN-LAST:event_JVisuLivroActionPerformed

    private void JCad_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_ClienteActionPerformed
        // TODO add your handling code here:
        new Cad_Autor().setVisible(true);
    }//GEN-LAST:event_JCad_ClienteActionPerformed

    private void JCad_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_LivroActionPerformed
        // TODO add your handling code here:
        new Cad_Livros().setVisible(true);
    }//GEN-LAST:event_JCad_LivroActionPerformed

    private void JCad_BiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_BiblioActionPerformed
        // TODO add your handling code here:
        new Cad_Bibliotecario().setVisible(true);
    }//GEN-LAST:event_JCad_BiblioActionPerformed

    private void JCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadAutorActionPerformed
        // TODO add your handling code here:
        new Cad_Autor().setVisible(true);
    }//GEN-LAST:event_JCadAutorActionPerformed

    private void JCad_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_CategoriaActionPerformed
        // TODO add your handling code here:
        new Cad_Categoria().setVisible(true);
    }//GEN-LAST:event_JCad_CategoriaActionPerformed

    private void JCad_EditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_EditoraActionPerformed
        // TODO add your handling code here:
        new Cad_Editora().setVisible(true);
    }//GEN-LAST:event_JCad_EditoraActionPerformed

    private void JVisuEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVisuEmprestimosActionPerformed
        new ListarEmprestimo().setVisible(true);
    }//GEN-LAST:event_JVisuEmprestimosActionPerformed

    private void JCad_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCad_EmprestimoActionPerformed
        // TODO add your handling code here:
        new Cad_Emprestimo().setVisible(true);
    }//GEN-LAST:event_JCad_EmprestimoActionPerformed

    private void JAlt_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_ClienteActionPerformed
        // TODO add your handling code here:
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_JAlt_ClienteActionPerformed

    private void JAlt_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_LivroActionPerformed
        // TODO add your handling code here:
        new ListarLivro().setVisible(true);
    }//GEN-LAST:event_JAlt_LivroActionPerformed

    private void JAlt_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_EmprestimoActionPerformed
        // TODO add your handling code here:
        new ListarEmprestimo().setVisible(true);
    }//GEN-LAST:event_JAlt_EmprestimoActionPerformed

    private void JAlt_BibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_BibliotecarioActionPerformed
        // TODO add your handling code here:
        new ListarBibliotecario().setVisible(true);
    }//GEN-LAST:event_JAlt_BibliotecarioActionPerformed

    private void JAlt_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_AutorActionPerformed
        // TODO add your handling code here:
        new ListarAutor().setVisible(true);
    }//GEN-LAST:event_JAlt_AutorActionPerformed

    private void JAlt_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_CategoriaActionPerformed
        // TODO add your handling code here:
        new ListarCategoria().setVisible(true);
    }//GEN-LAST:event_JAlt_CategoriaActionPerformed

    private void JAlt_EditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlt_EditoraActionPerformed
        // TODO add your handling code here:
        new ListarEditora().setVisible(true);
    }//GEN-LAST:event_JAlt_EditoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JAlt_Autor;
    private javax.swing.JMenuItem JAlt_Bibliotecario;
    private javax.swing.JMenuItem JAlt_Categoria;
    private javax.swing.JMenuItem JAlt_Cliente;
    private javax.swing.JMenuItem JAlt_Editora;
    private javax.swing.JMenuItem JAlt_Emprestimo;
    private javax.swing.JMenuItem JAlt_Livro;
    private javax.swing.JMenuItem JCadAutor;
    private javax.swing.JMenuItem JCad_Biblio;
    private javax.swing.JMenuItem JCad_Categoria;
    private javax.swing.JMenuItem JCad_Cliente;
    private javax.swing.JMenuItem JCad_Editora;
    private javax.swing.JMenuItem JCad_Emprestimo;
    private javax.swing.JMenuItem JCad_Livro;
    private javax.swing.JMenu JMenuAutor;
    private javax.swing.JMenu JMenuBiblio;
    private javax.swing.JMenu JMenuCategoria;
    private javax.swing.JMenu JMenuCliente;
    private javax.swing.JMenu JMenuEditora;
    private javax.swing.JMenu JMenuEmprestimo;
    private javax.swing.JMenu JMenuLivro;
    private javax.swing.JMenuItem JVisuAutor;
    private javax.swing.JMenuItem JVisuBiblio;
    private javax.swing.JMenuItem JVisuCategorias;
    private javax.swing.JMenuItem JVisuClientes;
    private javax.swing.JMenuItem JVisuEditoras;
    private javax.swing.JMenuItem JVisuEmprestimos;
    private javax.swing.JMenuItem JVisuLivro;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnBibliotecario;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditora;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnLivro;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
